### ISSUE TITLE
Support transactions

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-concurrency#23]
Let's write a `ThreadContextProvider` for transactions.

**Comment by FroMage** [comment]
I don't know the first thing about transactions except to add `@Transactional` whenever it complains, but I guess it would help if I could come up with a failing test to check that we have transaction propagation, this way you can test your code.

**Comment by FroMage** [comment]
I suppose we can consider that done @mmusgrov ?

**Comment by mmusgrov** [comment]
Closing since the SmallRye changes have been merged. I raised https://github.com/eclipse/microprofile-concurrency/pull/131 to add the relevant tests to the MP Concurrency TCK.
