### ISSUE TITLE
Spec requires to implement toString on ME and TC implementations

### ISSUE THREAD

**Issue by manovotn** [smallrye/smallrye-concurrency#27]
Specification now requires to implement `toString` method for `ManagedExecutor` and `ThreadContext`.
Resulting String definition is very vague except that for those used in CDI, the container has to include a `fully qualified name of the injection point from which the container produces the instance`.

Relevant spec javadocs are:
`ManagedExecutor` - https://github.com/eclipse/microprofile-concurrency/blob/master/api/src/main/java/org/eclipse/microprofile/concurrent/ManagedExecutor.java#L342-L350
`ThreadContext` - https://github.com/eclipse/microprofile-concurrency/blob/master/api/src/main/java/org/eclipse/microprofile/concurrent/ThreadContext.java#L430-L438

**Comment by FroMage** [comment]
Isn't it a bit crazy that the spec would specify the format of `toString()`?

**Comment by manovotn** [comment]
Well, the don't specify anything except for you to have it.
I think they wanted to use this to test equality of CDI injections (as you otherwise compare proxies) and they didn't want to make the settings publicly readable.

Either way, it won't hurt to have a `toString()` anyway.

**Comment by FroMage** [comment]
OK, whatever.
