### ISSUE TITLE
Expose UserTransaction to the TCK as a CDI bean

### ISSUE THREAD

**Issue by mmusgrov** [smallrye/smallrye-concurrency#33]
Follows up on #23. The MP Concurrency TCK should not rely on the presence of a CDI TransactionManager bean and UserTransaction is more standard. For example some implementations of the JTA 1.2 CDI extension do not expose TransactionManager in CDI and other implementations do not expose UserTransaction.

Therefore the SmallRye TCK should make UserTransaction available as a CDI bean.

**Comment by FroMage** [comment]
Fixed
